language: java
sudo: true

jdk:
  - oraclejdk8

dist: trusty

before_install:
  - ./gradlew wrapper --gradle-version=7.5 --distribution-type=bin
  - gradle -v

script:
  - ./gradlew build --scan -s
  - ./gradlew test build