language: java
sudo: required
jdk:
  - oraclejdk8
dist: trusty
before_install:
  - chmod +x gradlew
  - chmod +x gradle/wrapper/gradle-wrapper.jar
  - ./gradlew assemble
script:
  - ./gradlew test build